// The Following Lines are generated by the gentity tool 
// based on the input given in the entitytypes.xml file



export class Feedback{
	rating: Number,
	comment: String,
	course_code: String,
}


export class Schedule{
	day: Number,
	period: Number,
}


export class Attendance{
	staff_id: Number,
	roll_no: Number,
	period: Number,
	is_present: Boolean,
	is_fingerprint: Boolean,
	logged_time: DateTime,
	course_code: String,
}


export class Location{
	latitude: Number,
	longitude: Number,
	attendance: Attendance,
}


export class Staff{
	staff_name: String,
	staff_id_no: Number,
}


export class User{
	ukey: String,
	display_name: String,
	pub_key: String,
	sign_count: Number,
	username: String,
	emailid: String,
	rollno: Number,
	rp_id: String,
	icon_url: String,
	credential_id: String,
}


export class Course{
	course_name: String,
	course_code: String,
	users: User[],
	staff: Staff,
	schedules: Schedule[],
}


