# The Following Lines are generated by the gentity tool 
# based on the input given in the entitytypes.xml file



class FeedbackSchema(Schema):
	id = fields.Int(dump_only=True)
	rating = fields.Integer()
	comment = fields.Str()



class ScheduleSchema(Schema):
	id = fields.Int(dump_only=True)
	day = fields.Integer()
	period = fields.Integer()
	courses = fields.Nested('CourseSchema', many=True, exclude=('schedules', ))


class LocationSchema(Schema):
	id = fields.Int(dump_only=True)
	latitude = fields.Integer()
	longitude = fields.Integer()
	attendance = fields.Nested('AttendanceSchema', exclude=('location', ))


class AttendanceSchema(Schema):
	id = fields.Int(dump_only=True)
	staff_id = fields.Integer()
	roll_no = fields.Integer()
	period = fields.Integer()
	is_present = fields.Bool()
	is_fingerprint = fields.Bool()
	logged_time = fields.DateTime()
	location = fields.Nested('LocationSchema', exclude=('attendance',))



class StaffSchema(Schema):
	id = fields.Int(dump_only=True)
	staff_name = fields.Str()
	staff_id_no = fields.Integer()
	course = fields.Nested('CourseSchema', exclude=('staff', ))


class UserSchema(Schema):
	id = fields.Int(dump_only=True)
	ukey = fields.Str()
	display_name = fields.Str()
	pub_key = fields.Str()
	sign_count = fields.Integer()
	username = fields.Str()
	emailid = fields.Str()
	rollno = fields.Integer()
	rp_id = fields.Str()
	icon_url = fields.Str()
	credential_id = fields.Str()
	courses = fields.Nested('CourseSchema', many=True, exclude=('users', ))


class CourseSchema(Schema):
	id = fields.Int(dump_only=True)
	course_name = fields.Str()
	course_code = fields.Str()
	users = fields.Nested('UserSchema', many=True, exclude=('courses',))
	staff = fields.Nested('StaffSchema', exclude=('course',))
	schedules = fields.Nested('ScheduleSchema', many=True, exclude=('courses',))



