# The Following Lines are generated by the gentity tool 
# based on the input given in the entitytypes.xml file



class Testentity4Schema(Schema):
	attr121 = fields.Integer()
	attr212 = fields.Str()

	testentities = fields.Nested('TestentitySchema', many=True, exclude=('testentity4', ))

class Testentity3Schema(Schema):
	attr121 = fields.Str()
	attr212 = fields.Str()

	testentity = fields.Nested('TestentitySchema', exclude=('testentity3', ))

class Testentity1Schema(Schema):
	attr11 = fields.Integer()
	attr21 = fields.Integer()

	testentity = fields.Nested('TestentitySchema', exclude=('testentity1', ))

class TestentitySchema(Schema):
	attr1 = fields.Integer(required=True, validate=validate.Length(max=40))
	attr2 = fields.Str()
	testentity1 = fields.Nested('Testentity1Schema', exclude=('testentity',))
	testentity3s = fields.Nested('Testentity3Schema',many=True, exclude=('testentity',))


