# The Following Lines are generated by the gentity tool 
# based on the input given in the entitytypes.xml file




user_course = db.Table("user_course",
	db.Column("course_id", db.Integer, db.ForeignKey("course.id")),
	db.Column("user_id", db.Integer, db.ForeignKey("user.id")))


staff_course = db.Table("staff_course",
	db.Column("course_id", db.Integer, db.ForeignKey("course.id")),
	db.Column("staff_id", db.Integer, db.ForeignKey("staff.id")))


schedule_course = db.Table("schedule_course",
	db.Column("course_id", db.Integer, db.ForeignKey("course.id")),
	db.Column("schedule_id", db.Integer, db.ForeignKey("schedule.id")))

class Course(db.Model):
	__tablename__ = 'course'
	id = db.Column(db.Integer, primary_key=True)
	course_name = db.Column(db.String(40))
	course_code = db.Column(db.String(40))
	users = db.relationship("User", secondary=user_course, backref=db.backrefs("courses") )
	staffs = db.relationship("Staff", secondary=staff_course, backref=db.backrefs("courses") )
	schedules = db.relationship("Schedule", secondary=schedule_course, backref=db.backrefs("courses") )


class User(db.Model):
	__tablename__ = 'user'
	id = db.Column(db.Integer, primary_key=True)
	ukey = db.Column(db.String(40))
	display_name = db.Column(db.String(40))
	pub_key = db.Column(db.String(40))
	sign_count = db.Column(db.Integer)
	username = db.Column(db.String(40))
	email_id = db.Column(db.String(40))
	roll_no = db.Column(db.Integer)
	rp_id = db.Column(db.String(40))
	icon_url = db.Column(db.String(40))


class Staff(db.Model):
	__tablename__ = 'staff'
	id = db.Column(db.Integer, primary_key=True)
	staff_name = db.Column(db.String(40))
	staff_id_no = db.Column(db.Integer)


class Attendance(db.Model):
	__tablename__ = 'attendance'
	id = db.Column(db.Integer, primary_key=True)
	staff_id = db.Column(db.Integer)
	roll_no = db.Column(db.Integer)
	period = db.Column(db.Integer)
	is_present = db.Column(db.Boolean)
	is_fingerprint = db.Column(db.Boolean)
	logged_time = db.Column(db.DateTime)


class Schedule(db.Model):
	__tablename__ = 'schedule'
	id = db.Column(db.Integer, primary_key=True)
	day = db.Column(db.Integer)
	period = db.Column(db.Integer)


